### ISSUE TITLE
Add sentiment analysis to song class

### ISSUE THREAD

**Issue by malctaylor15** [malctaylor15/Song_Lyrics_NLP#5]
Use textblob or other API to add sentiment analysis of song lyrics 
-- https://pypi.python.org/pypi/textblob might be useful

**Comment by trackoverxc** [comment]
Create function within song class for this

**Comment by trackoverxc** [comment]
We may need to clean the string input for the sentiment module to function depending on the one chosen

**Comment by trackoverxc** [comment]
https://elitedatascience.com/python-nlp-libraries#textblob
Page listing TextBlob as great for sentiment

**Comment by trackoverxc** [comment]
http://rwet.decontextualize.com/book/textblob/
Tutorial for TextBlob

**Comment by trackoverxc** [comment]
Finished 20171211 w/ Malcolm
